/**
 * Lists every route.ts under src/server/api in src/generated/api-routes.ts, the
 * table the on-device router (src/server/local-server.ts) answers `/api/...`
 * calls from. A route file is all it takes to add an endpoint: `[id]` folders
 * become `:id` parameters.
 */
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative, sep } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const apiDir = join(root, "src/server/api");

function routeFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return routeFiles(path);
    return entry.name === "route.ts" ? [path] : [];
  });
}

const routes = routeFiles(apiDir)
  .map((file) => {
    const folders = relative(apiDir, file).split(sep).slice(0, -1);
    const pattern = "/api/" + folders.map((f) => f.replace(/^\[(\w+)\]$/, ":$1")).join("/");
    return { pattern, module: "@/server/api/" + folders.join("/") + "/route" };
  })
  .sort((a, b) => a.pattern.localeCompare(b.pattern));

mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(
  join(root, "src/generated/api-routes.ts"),
  `// Generated by scripts/api-routes.mjs from src/server/api. Do not edit.\n` +
    routes.map((r, i) => `import * as r${i} from "${r.module}";\n`).join("") +
    `\n/** URL pattern → that route file's exported GET/POST/… handlers. */\n` +
    `export const ROUTES: [string, object][] = [\n` +
    routes.map((r, i) => `  ["${r.pattern}", r${i}],\n`).join("") +
    `];\n`,
);
console.log(`api-routes: listed ${routes.length} routes`);
