/**
 * Runs after `prisma generate`. Makes the generated client and the migrations
 * usable inside the app's WebView, where there is no server and no Node.
 *
 * 1. The "workerd" client loads Prisma's query compiler with
 *    `import("./query_compiler_bg.wasm?module")`, which only Cloudflare's
 *    runtime understands. Swap it for the base64 build Prisma also ships and
 *    compile it with the browser's own WebAssembly API.
 * 2. Bundle every prisma/migrations/<name>/migration.sql into
 *    src/generated/migrations.ts, so the app can bring the on-device
 *    database up to date on start-up (src/lib/local-db.ts).
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;

const classFile = join(root, "src/generated/prisma/internal/class.ts");
const source = readFileSync(classFile, "utf8");
const loader = /config\.compilerWasm = \{[\s\S]*?\n\}/;
if (!loader.test(source)) throw new Error(`prisma-browser: compilerWasm block not found in ${classFile}`);
writeFileSync(
  classFile,
  source.replace(
    loader,
    `config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_bg.postgresql.mjs"),

  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_bg.postgresql.wasm-base64.mjs")
    const binary = atob(wasm)
    const bytes = new Uint8Array(binary.length)
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
    return await WebAssembly.compile(bytes)
  }
}`,
  ),
);

const dir = join(root, "prisma/migrations");
const migrations = readdirSync(dir)
  .filter((name) => existsSync(join(dir, name, "migration.sql")))
  .sort()
  .map((name) => ({ name, sql: readFileSync(join(dir, name, "migration.sql"), "utf8") }));
writeFileSync(
  join(root, "src/generated/migrations.ts"),
  `// Generated by scripts/prisma-browser.mjs from prisma/migrations. Do not edit.\n` +
    `export const MIGRATIONS: { name: string; sql: string }[] = ${JSON.stringify(migrations, null, 2)};\n`,
);
console.log(`prisma-browser: patched the client, bundled ${migrations.length} migrations`);
